### ISSUE TITLE
Number of cores not recognised in `diamond_protein_to_protein_best_hits()`

### ISSUE THREAD

**Issue by LotharukpongJS** [drostlab/rdiamond#1]
Hi @HajkD ,

I was using `diamond_protein_to_protein_best_hits()` and I noticed that the `diamond_protein_to_protein_best_hits()` and probably the `diamond_protein_to_protein_best_reciprocal_hits()` do not recognise the number of cores added to the parameter `cores`.

```R
> best_rec_hits <- rdiamond::diamond_protein_to_protein_best_hits(
+   query = file_path.ENSEMBL, 
+   subject = file_path.REFSEQ,
+   cores = 8)
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: _uniprot_downloads/proteomes/Caenorhabditis_elegans_protein_uniprot.faa.gz
Opening the database file...  [0.028s]
Loading sequences...  [0.093s]
Masking sequences...  [1.337s]
Writing sequences...  [0.02s]
Hashing sequences...  [0.003s]
Loading sequences...  [0s]
Writing trailer...  [0s]
Closing the input file...  [0s]
Closing the database file...  [0.009s]

Database sequences  19827
  Database letters  8133982
     Database hash  6a425f34faeffe53753689f5f3d11321
        Total time  1.494000s
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
```
_etc._

I believe this is because the internal call of `rdiamond::diamond_protein_to_protein()` in these two functions doesn't set the `cores` parameter, thus defaulting to `cores = 1`. This can be resolved by adding this parameter to the two functions.

https://github.com/drostlab/rdiamond/blob/27a4eca1b28d1edd2e257d34504a8432c0feb7ac/R/diamond_protein_to_protein_best_hits.R#L98-L111

I will try to change this and make a pull request when I have the time.

Best,
Sodai

**Comment by HajkD** [comment]
Wonderful, @LotharukpongJS! Excellent catch!

It's merged now and works beautifully!

With many thanks and very best wishes,
Hajk
